- name: multiple playbooks
  hosts: localhost
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "Playbook 1 and task1"

  - name: play1 and task2
    ansible.builtin.debug:
      msg: "Playbook 1 and task 2"

  - name: play2 and task1
    ansible.builtin.debug:
      msg: "Playbook 2 and task1"
  - name: play1 and task2
    ansible.builtin.debug:
      msg: "Playbook 1 and task 2"