- name: playbook variables
  hosts: localhost
  vars:
    NAME: lakshmi
    AGE:  26
    GENDER: female
  tasks:
  - name: variables in -playbook
    vars:
      NAME: reddy
      AGE:  20
      GENDER: male

    ansible.builtin.debug:
      msg: "my name is {{ NAME }} and my gender is {{ GENDER }} and my age is {{ AGE }}"


  - name: variables in local play
    ansible.builtin.debug:
       msg: "my name is {{ NAME }} and my gender is {{ GENDER }} and my age is {{ AGE }}"
