- name: playbook variables
  hosts: local
  connection: local
  vars:
    NAME: Lakshmi
    AGE: 24
    GENDER: Female
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} and my age is {{ AGE }} and my gender is {{ GENDER }}"
  - name: print the variables info again
    ansible.builtin.debug:
        msg: "My name is {{ NAME }} and my age is {{ AGE }} and my gender is {{ GENDER }}"