- name: tasks and multiple variables
  hosts: localhost
  vars:
    NAME: lakshmi
    AGE:  20
    GENDER: female
  tasks:
  - name: print the global variables
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} and my gender is {{ GENDER }} and my age is {{ AGE }}"
  
  - name: Print the local variables
    vars:
    NAME: reddy
    AGE:  20
    GENDER: male
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} and my gender is {{ GENDER }} and my age is {{ AGE }}"
