- name: Tasks and variable
  hosts: local
  connection: local
  vars:
    NAME: Lakshmi
    AGE: 24
    GENDER: Female
  tasks:
  - name: printing global variables
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} and my age is {{ AGE }} and my gender is {{ GENDER }}"
  - name: printing local variables
    vars:
      NAME: Reddy
      AGE: 25
      GENDER: male
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} and my age is {{ AGE }} and my gender is {{ GENDER }}"
