- name: variables from the files  
  hosts: local
  connection: local
  vars_files:
    -user.yaml
  tasks:
  - name: print the user info
    ansible.builtin.debug:
      msg: "My name is {{ NAME }} and my age is {{ AGE }} and my gender is {{ GENDER }}"
