- name: Files and variables
  hosts: local
  connection: local
  var_files:
    - user.yaml
  tasks:
  - name: Print user details
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} and my gender is {{ GENDER }} and my age is {{ AGE }}"