- name: lopp
  hosts: local
  connection: local
  tasks: 
  - name: print the names in loop
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
    - ram
    - sita
    - suresh
    - mahesh