- name: installing and unstalling packages
  host: frontend
  become: yes
  tasks:
  - name: installing and unstalling packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'present'}
    - { name: 'mysql', state: 'absent'}
    - { name: 'zip', state: 'absent'}