- name: functions in ansible
  hosts: local
  connection: local
  vars:
    persons: "ramesh,suresh,ram,sita"
  tasks:
  - name: check undefinaed variables
    ansible.builtin.debug:
      msg: "hello ,{{ person | default('Ramesh') }}"
  - name: print persons names
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"
  
  - name: convert map into list
    vars:
     course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: " Hello couser info {{ course | dict2items }} "

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: " {{ course | items2dict }} "
  - name: convert lower case to upper case
    vars:
      name: "lakshmi reddy"
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert upper case to lower case
    vars:
      name: "LAKSHMI"
    ansible.builtin.debug:
      msg: "{{ name | lower }}"
