- name: functions in ansible
  hosts: local
  connection: local
  vars:
  persons: "ramesh,suresh,ram,sita"
  tasks:
  - name: check undefinaed variables
    ansible.builtin.debug:
      msg: "hello ,{{ person | default('Ramesh')}"
  
 